# -*- coding: utf-8 -*-
"""aulaTesteDados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jis4fF5MVScIqlHPZ_7sve0JskiyJKYh

TEMA: Como prever o futuro com dados?

OBJETIVO: Usar Pandas, NumPy e Matplotlib para fazer uma previsão com regressão linear simples.

Hoje vamos simular uma situação real de Ciência de Dados: a previsão de vendas futuras com base em dados históricos. Vamos aprender como isso pode ser feito com ferramentas que todo cientista de dados utiliza: Pandas, NumPy e Matplotlib.

Apresentação dos dados

Dataset fictício diretamente no código.
"""

import pandas as pd

# Dados fictícios de vendas por mês
dados = {
    'Mês': ['Jan', 'Fev', 'Mar', 'Abr', 'Mai'],
    'Vendas': [100, 120, 110, 150, 140]
}

df = pd.DataFrame(dados)
df

"""Gráfico e exploração da tendência"""

import matplotlib.pyplot as plt

df['Índice'] = range(1, len(df) + 1)  # Representação numérica dos meses

plt.plot(df['Índice'], df['Vendas'], marker='o')
plt.title('Vendas por Mês')
plt.xlabel('Mês (índice)')
plt.ylabel('Vendas')
plt.grid(True)

plt.show()

"""Regressão linear simples"""

import numpy as np

# Variáveis independentes e dependentes
X = df['Índice']
y = df['Vendas']

# Cálculo dos coeficientes da reta (y = a*x + b)
# Tendência linear --> np.polyfit()
a, b = np.polyfit(X, y, 1)

print(f"Equação da reta: y = {a:.2f}x + {b:.2f}")

# Previsão para o mês 6 (junho)
mes_6 = 6
previsao = a * mes_6 + b
print(f"Previsão de vendas para junho: {previsao:.2f}")

"""Visualização da previsão"""

# Plot original + previsão
plt.plot(X, y, 'o', label='Dados observados')
plt.plot(range(1, 8), [a * x + b for x in range(1, 8)], '-', label='Reta da regressão')
plt.axvline(x=6, color='gray', linestyle='--')
plt.axhline(y=previsao, color='red', linestyle='--', label='Previsão Junho')
plt.legend()
plt.xlabel('Mês (índice)')
plt.ylabel('Vendas')
plt.title('Previsão com Regressão Linear')
plt.grid(True)
plt.show()